framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        providers:


# framework:
#     default_locale: en
#     translator:
#         default_path: '%kernel.project_dir%/translations'
#         fallbacks:
#             - en
#         providers:
